//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientsMSSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCode
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<int> client_ID { get; set; }
        public Nullable<int> code_ID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Code Code { get; set; }
    }
}
