//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientsMSSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientCodes = new HashSet<ClientCode>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime DateOfAccident { get; set; }
        public string Attorney { get; set; }
        public string PropertyDamage { get; set; }
        public string InsuranceCompany { get; set; }
        public string Liability { get; set; }
        public Nullable<System.DateTime> Mri { get; set; }
        public string Consultation { get; set; }
        public string PainControl { get; set; }
        public string ShockWave { get; set; }
        public Nullable<System.DateTime> LiabilityDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientCode> ClientCodes { get; set; }
    }
}
